version: "3.8"

services:
  app:
    build: .
    container_name: "apitestcontelelabs-server"
    command: sh -c "npm run migrate && npm run seed && npm start"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: apitestcontelelabs-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres